export const EMAIL_REQUIRED = 'Email is required'
export const EMAIL_INVALID = 'Email is invalid'
export const PASSWORD_REQUIRED = 'Password is required'
export const PASSWORD_INVALID = 'Password must be at least 6 characters long'
export const PASSWORDS_DIFFERENT = 'Passwords do not match'
export const ACCOUNT_TYPE_REQUIRED = 'Account type is required'
export const COMPANY_NAME_REQUIRED = 'Company name is required'
